### ISSUE TITLE
engin.Find()

### ISSUE THREAD

**Issue by coolmandar** [go-xorm/manual-en-US#5] opened 2016-03-16 10:35 UTC
Please provide example to get list of table data using engine.Find(). I have tried with various example but exception occurred to set data of property value

**Comment by lunny** [comment] 2016-03-16 14:53
I think you can find the example here https://github.com/go-xorm/xorm/blob/master/examples/conversion.go#L70

**Comment by lunny** [comment] 2016-07-14 01:24
I will close this and you can reopen it if the issue is still not resolved.

**Closed as completed by lunny** 2016-07-14 01:24 UTC
